services:
  postgres:
    image: postgres:17
    container_name: url-shortener-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: url_shortener
      POSTGRES_PASSWORD: url_shortener_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
