spring:
  application:
    name: url-shortener

  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: url_shortener
    password: url_shortener_dev

  jpa:
    hibernate:
      ddl-auto: update


    open-in-view: false

    properites:
      hiberante:
        formate_sql: true
